### ISSUE TITLE
Upgrade to github.com/golang-jwt/jwt/v5

### ISSUE THREAD

**Issue by gnuletik** [labstack/echo-jwt#8]
jwt/v5 is out: https://github.com/golang-jwt/jwt/releases/tag/v5.0.0

Is there plan to move this middleware to golang-jwt/jwt/v5 ?

**Comment by aldas** [comment]
Yep, I do not have much time in coming couple of weeks but maybe you @gnuletik  want to with try with PR? Looking at release notes it maybe is not that radical change after all.

**Comment by gnuletik** [comment]
Thanks for the fast feedback! I don't have much time in coming weeks neither but will reconsider later if possible.

**Comment by whkelvin** [comment]
Just created a pr for this. I updated jwt to v5, ran `go test` and tested out the snippet in the readme. This is my first time contributing, let me know if I am missing anything :smile:

**Comment by aldas** [comment]
This can be closed - v4.2.0 is using `v5`. See https://github.com/labstack/echo-jwt/releases/tag/v4.2.0
